### ISSUE TITLE
Game crashed, screen went black, some sort of infinite loop

### ISSUE THREAD

**Issue by KMFSousa** [quibbble/carcassonne#4]
One of our players said in the console it complained about a loop or something returning badly. I wish I could help more but we never we're able to recover the game 

https://carcassonne.quibbble.com/khaki-cords-9 was our code

**Comment by freglyc** [comment]
Hey @KMFSousa is this still an issue for you? I've gone to the link you posted and the game loads and appears just fine on my end. If this is still a problem or you find another link that has this issue please let me know. Thanks!
