### ISSUE TITLE
Text is unreadable and others hard to reed in game rules

### ISSUE THREAD

**Issue by KMFSousa** [quibbble/carcassonne#5]
The app was dark mode for me, I assume this was due to adjusting to my system? or maybe it was an extension but the game didn't handle whatever it was well and I couldn't read some of the rules without highlighting them

**Comment by freglyc** [comment]
@KMFSousa could you maybe post a screenshot of the issue you are facing to provide me with a little more detail? If this is still and issue I am happy to take a look and see what I can do to adjust the rules page to make it more readable.

**Comment by freglyc** [comment]
closing for now
