### ISSUE TITLE
Export game as json file, or something, to continue at a later point in time or in case of error

### ISSUE THREAD

**Issue by KMFSousa** [quibbble/carcassonne#6]
We ran into an issue that lost our progress and that was quite sad, while it's best to play any game in one session sometimes we only have small timeslots. It'd be great to be able to export the game and pick up later again by importing it

**Comment by freglyc** [comment]
Hey @KMFSousa thanks for opening the issue. Currently all games are closed and should be saved to a DB after 30 minutes of inactivity. Returning to the game at a later date should load the game and allow you to continue where you left off. 

If your game was not saved after returning to the same link then that is an issue and I would be interested in taking a look if you still have that same game link. If you no longer have that link but run into the same issue please let me know here or in our [discord](https://discord.com/invite/VKvjutuhUp). I will be closing this issue for now unless further information is provided. Thanks!

EDIT: I see that you posted a link in #4 so will take a look at that when I have some time and will continue the discussion there.
