### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by MatzE-sch** [quibbble/carcassonne#9]
I think keyboard shortcuts would be a great idea.
Not only to need to use the mouse less often to to skip not placing a token but also on the steamdeck where i like to play ist most.
beeing able to map functionalities like choosing a team and skipping placing a token to controller buttons would make playing faster and easier. Switching to the player which currently needs to play would also be very nice if you play on a single device :)

I started working on those shortcuts in my forks, and will make a pull request as soon as I have tested the integration of [Boardgame](https://github.com/MatzE-sch/boardgame) with the [Carcassonne shortcuts implementation](https://github.com/MatzE-sch/carcassonne/tree/feat-shortcuts)

**Comment by MatzE-sch** [comment]
I tested the feature locally.
Pull requests are there:
https://github.com/quibbble/boardgame/pull/10
https://github.com/quibbble/carcassonne/pull/11

**Comment by freglyc** [comment]
These changes have been merged. Thanks for your work in adding those shortcuts in :)
